CREATE DATABASE IF NOT EXISTS algebta_conntacts DEFAULT CHARACTER SET utf8
COLLARE utf8_general_ci;

USE algebra_conntacts;

CREATE TABLE IF NOT EXISTS users(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(20) NOT NULL UNIQUE,
	password VARCHAR(64) NOT NULL,
	salt VARCHAR(32) NOT NULL,
	name VARCHAR(50) NULL
	joined TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	role_id INT UNSIGNED NOT NULL 
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS roles(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(20) NOT NULL, 
	permissions TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sessions(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	hash VARCHAR (64) NOT NULL,
	user_id INT UNSIGNED NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXIST person(
		id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(128) NOT NULL,
		user_id INT UNSIGNED NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS contacts(
			id INT UNSIGNED NOT NULL AUTO_INCREMENT


